/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.femass.principal;

import org.femass.gui.GuiCliente;
import org.femass.gui.GuiCompras;
import org.femass.gui.GuiFornecedor;
import org.femass.gui.GuiProduto;

/**
 *
 * @author leome
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        MnuCliente = new javax.swing.JMenuItem();
        MnuFornecedor = new javax.swing.JMenuItem();
        MnuProduto = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MnuCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastro");

        MnuCliente.setMnemonic('s');
        MnuCliente.setText("Cliente");
        MnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuClienteActionPerformed(evt);
            }
        });
        fileMenu.add(MnuCliente);

        MnuFornecedor.setText("Fornecedor");
        MnuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuFornecedorActionPerformed(evt);
            }
        });
        fileMenu.add(MnuFornecedor);

        MnuProduto.setText("Produto");
        MnuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuProdutoActionPerformed(evt);
            }
        });
        fileMenu.add(MnuProduto);

        menuBar.add(fileMenu);

        jMenu1.setText("Pedido");

        MnuCompra.setText("Compra");
        MnuCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCompraActionPerformed(evt);
            }
        });
        jMenu1.add(MnuCompra);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuClienteActionPerformed
//        GuiCliente guiCliente = new GuiCliente();

        GuiCliente guiCliente = new GuiCliente();
        if(guiCliente==null){
            return;
        }
        desktopPane.add(guiCliente);
        guiCliente.setVisible(true);


    }//GEN-LAST:event_MnuClienteActionPerformed

    private void MnuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuFornecedorActionPerformed
        GuiFornecedor guiFornecedor = new GuiFornecedor();
        if(guiFornecedor==null){
            return;
        }
        desktopPane.add(guiFornecedor);
        guiFornecedor.setVisible(true);
    }//GEN-LAST:event_MnuFornecedorActionPerformed

    private void MnuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuProdutoActionPerformed
        GuiProduto guiProduto = new GuiProduto();
        if(guiProduto==null){
            return;
        }
        desktopPane.add(guiProduto);
        guiProduto.setVisible(true);
    }//GEN-LAST:event_MnuProdutoActionPerformed

    private void MnuCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCompraActionPerformed
        GuiCompras guiCompras = new GuiCompras();
        if(guiCompras==null){
            return;
        }
        desktopPane.add(guiCompras);
        guiCompras.setVisible(true);
    }//GEN-LAST:event_MnuCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuCliente;
    private javax.swing.JMenuItem MnuCompra;
    private javax.swing.JMenuItem MnuFornecedor;
    private javax.swing.JMenuItem MnuProduto;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
